# Kubernetes job template for robot team
# Do not deploy this on the G1!
apiVersion: batch/v1
kind: Job
metadata:
  name: robot-team-yourname # name of pod for job followed by hash
  namespace: workspace-crab # your namespace, don't change
spec:
  ttlSecondsAfterFinished: 86400  # Auto-cleanup after 24 hours, adjust as needed
  template:
    spec:
      
      restartPolicy: OnFailure # Jobs require OnFailure or Never, not Always
      
      securityContext: # starts you as worker
        runAsUser: 1000
        runAsGroup: 1000
      
      imagePullSecrets:
        - name: ghcr-secret # lets you pull the image from the private repository
      
      containers:
        
        - name: robot-team # internal name of the container
          image: ghcr.io/mikethebuddy/robot-team-image:latest # docker image with verison
          imagePullPolicy: Always
          
          ports:
            - containerPort: 5900
              name: vnc
          
          volumeMounts:

            - name: worker-yourname # your personal persistent storage volume
              mountPath: /home/worker

            - name: crab-shared # small shared volume mount for code
              mountPath: /CRAB

            - name: crab-datasets # large shared volume mount for datasets and large pretrained models
              mountPath: /CRAB/datasets

            - name: gitconfig # persistent git settings
              mountPath: /home/worker/.gitconfig
              subPath: .gitconfig

            - name: git-keys # your personal SSH/GPG keys
              mountPath: /home/worker/.ssh
              readOnly: true

          resources: # specify gpu requests here - be reasonable
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
      volumes:

        - name: worker-yourname # your personal persistent storage volume
          persistentVolumeClaim:
            claimName: worker-yourname

        - name: crab-shared # small shared volume mount for code
          persistentVolumeClaim:
            claimName: crab-shared

        - name: crab-datasets # large shared volume mount for datasets and large pretrained models
          persistentVolumeClaim:
            claimName: crab-datasets

        - name: gitconfig # persistent git settings
          configMap:
            name: gitconfig-yourname

        - name: git-keys # your personal SSH/GPG keys
          secret:
              secretName: yourname-keys
              defaultMode: 0600  # SSH requires strict permissions